Multiwfn 1.fchk < ESPpt.txt
mv -f vtx.pdb vtx1.pdb
mv -f mol.pdb mol1.pdb
Multiwfn 2.fchk < ESPpt.txt
mv -f vtx.pdb vtx2.pdb
mv -f mol.pdb mol2.pdb
Multiwfn 3.fchk < ESPpt.txt
mv -f vtx.pdb vtx3.pdb
mv -f mol.pdb mol3.pdb
Multiwfn 4.fchk < ESPpt.txt
mv -f vtx.pdb vtx4.pdb
mv -f mol.pdb mol4.pdb